config/routes.rb
HarvestHelper::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "users/show"

  devise_for :users, :controllers => {
                        :sessions => 'my_devise/sessions',
                        :omniauth_callbacks => "my_devise/omniauth_callbacks"
                    }

  devise_scope :user do
    get '/users/auth/:provider' => 'my_devise/omniauth_callbacks#passthru'
  end
  
  root to: 'static_pages#home'
  
  resources :users, only: [:show]
	#resources :sessions, only: [:new, :create, :destroy]
  resources :garden_devices
  resources :device_schedules, only: [:create, :destroy]
  resources :message_boards, only: [:index, :show]
  resources :posts, only: [:show, :new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  
  match '/about', to: 'static_pages#about'
  match '/add_device', to: 'garden_devices#new'
  
  match '/data_receiver', to: 'garden_device_service#receive_data', via: :post
  match '/polling_service', to: 'garden_device_service#poll_for_updates', via: :post
  
  match '/charts/:action', to: 'charts#overview', as: :charts
  match "/garden_devices/:id/graphs" => "garden_devices#graphs", :as => 'graphs'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  belongs_to :post
  belongs_to :user
  
  validates :content,
              presence: true
  validates :post_id,
              presence: true
  validates :user_id,
              presence: true
end

app/models/device_schedule.rb
class DeviceSchedule < ActiveRecord::Base
  attr_accessible :sensor_flag, :frequency, :is_enabled
  belongs_to :garden_device
  
  validates :garden_device,
              presence: true
  validates :sensor_flag,
              presence: true
              
  def display_time
    self.is_enabled ? "Every " + self.frequency.to_s + " minute".pluralize : "---"
  end
end

app/models/garden_data.rb
class GardenData < ActiveRecord::Base
  attr_accessible :humidity, :temperature, :lux, :sensor_time
  validates :garden_device, :sensor_time,
              presence: true
  belongs_to :garden_device
end

app/models/garden_device.rb
class GardenDevice < ActiveRecord::Base
  attr_accessible :name, :serial_number, :timezone, :latitude, :longitude
  attr_accessible :name, :serial_number, :timezone, :latitude, :longitude, :user_id, as: :admin
  
  belongs_to :user
  has_many :garden_datas
  has_many :device_schedules
  
  before_save { |device| device.serial_number = serial_number.downcase }
  
  validates :name, :user, :timezone,
              presence: true
  validates :serial_number,
              presence: true,
              uniqueness: { case_sensitive: false }
  validates :name, uniqueness: true
  paginates_per 10
end

app/models/message_board.rb
class MessageBoard < ActiveRecord::Base
  attr_accessible :name
  has_many :posts
  
  validates :name,
              presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
  belongs_to :message_board
  belongs_to :user
  has_many :comments
  
  validates :content,
              presence: true
  validates :title,
              presence: true
  validates :message_board_id,
              presence: true
  validates :user_id,
              presence: true
end

app/models/schedule_type_lookup.rb
class ScheduleTypeLookup < ActiveRecord::Base
  attr_accessible :flag, :name
  validates :name, :presence => true
  validates :name, :uniqueness => true
	validates :flag, :presence => true
	validates :flag, :uniqueness => true  
  def get_name
    self.name ||= "No Name"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :omniauth_providers => [:facebook]
         #:recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :provider, :uid
  
  # attr_accessible :title, :body
    validates :email, :password, :first_name, :last_name,
              presence: true
              
  has_many :garden_devices
  has_many :posts
  has_many :comments
  
  def get_full_name
    first = self.first_name
    last = self.last_name
    first + " " + last rescue nil
  end
  
  def get_first_name
    self.first_name rescue nil
  end
  
  def get_last_name
    self.last_name rescue nil
  end
  
  def to_s
   get_full_name
  end
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(first_name:auth.extra.raw_info.first_name,
                          last_name:auth.extra.raw_info.last_name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    if !signed_in?
      redirect_to root_path
    else
      @post = Post.find(params[:id])
      @comment = Comment.new
    end
  end

  def new
    if !signed_in?
      redirect_to root_path
    else
      @post = Post.new
      @message_board_id = params[:board_id]
    end
  end

  def create
    @post = current_user.posts.build(params[:post])
    @post.message_board_id = params[:message_board_id]
    if @post.save
      redirect_to @post
    else
      puts @post.errors.messages
      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
  def google_chart(action, height, params ={})
    params[:format] ||= :json
    path = charts_path(action, params)
    content_tag(:div, :'data-chart' => path, :style => "height: #{height}px; width:100%;") do
      label_tag('loading')
    end
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/garden_datas_helper.rb
module GardenDatasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HarvestHelper
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "charts"
    = javascript_include_tag "validation"
    = csrf_meta_tags
  %body
    = render 'layouts/shares/topbar'
    .wrapper
      .container
        .row
          .span12
            .well= yield
      .push     
    = render 'layouts/shares/footer'

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title HarvestHelper
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "charts"
    = javascript_include_tag "validation"
    = csrf_meta_tags
  %body
    = render 'layouts/shares/topbar'
    .wrapper
      .container
        .row
          .span12
            = yield
      .push
    = render 'layouts/shares/footer'

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title HarvestHelper
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "charts"
    = javascript_include_tag "validation"
    = csrf_meta_tags
  %body
    = render 'layouts/shares/topbar'
    .wrapper
      .container
        .row
          .span12.home-style
            = yield
      .push
    = render 'layouts/shares/footer'
    

app/views/layouts/shares/_footer.html.haml
%footer
  .footer
    = "Copyright © 2012 - #{Time.now.year}"
    = link_to "Drexel University - Computer Science", "http://cs.drexel.edu"
    = ". All Rights Reserved."

app/views/layouts/shares/_topbar.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      %a.brand{:href => "#"}Harvest Helper
      %ul.nav
        %li
          = link_to 'Home', root_path
        %li
          = link_to 'About', about_path
        - if user_signed_in?
          %li
            = link_to 'My Devices', garden_devices_path
          %li
            = link_to 'Forums', message_boards_path
      %ul.nav.pull-right
        - if user_signed_in?
          %li
            = link_to current_user.get_full_name, current_user
          %li
            = link_to "My Profile", users_show_path
          %li
            = link_to 'Sign Out', destroy_user_session_path, method: 'delete'
        - else
          %li
            = link_to 'Sign In', new_user_session_path

app/views/shared/_user_error_messages.html.haml
- if @user.errors.any?
  %p
    This form contains
    = pluralize(@user.errors.count, 'error')
  %ul
    - @user.errors.full_messages.each do |message|
      = '* ' + message