config/routes.rb
HarvestHelper::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "users/show"

  devise_for :users, :controllers => {
                        :sessions => 'my_devise/sessions',
                        :omniauth_callbacks => "my_devise/omniauth_callbacks"
                    }

  devise_scope :user do
    get '/users/auth/:provider' => 'my_devise/omniauth_callbacks#passthru'
  end
  
  root to: 'static_pages#home'
  
  resources :users, only: [:show]
	#resources :sessions, only: [:new, :create, :destroy]
  resources :garden_devices
  resources :device_schedules, only: [:create, :destroy]
  resources :message_boards, only: [:index, :show]
  resources :posts, only: [:show, :new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  
  match '/about', to: 'static_pages#about'
  match '/add_device', to: 'garden_devices#new'
  
  match '/data_receiver', to: 'garden_device_service#receive_data', via: :post
  match '/polling_service', to: 'garden_device_service#poll_for_updates', via: :post
  
  match '/charts/:action', to: 'charts#overview', as: :charts
  match "/garden_devices/:id/graphs" => "garden_devices#graphs", :as => 'graphs'
end

app/models/garden_device.rb
class GardenDevice < ActiveRecord::Base
  attr_accessible :name, :serial_number, :timezone, :latitude, :longitude
  attr_accessible :name, :serial_number, :timezone, :latitude, :longitude, :user_id, as: :admin
  
  belongs_to :user
  has_many :garden_datas
  has_many :device_schedules
  
  before_save { |device| device.serial_number = serial_number.downcase }
  
  validates :name, :user, :timezone,
              presence: true
  validates :serial_number,
              presence: true,
              uniqueness: { case_sensitive: false }
  validates :name, uniqueness: true
  paginates_per 10
end

app/controllers/garden_devices_controller.rb
class GardenDevicesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @garden_devices = current_user.garden_devices.page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @garden_devices }
    end
  end
  
  def show
    @garden_device = GardenDevice.find(params[:id])
    @device_schedule = DeviceSchedule.new
  end
  
  def new
    @garden_device = GardenDevice.new
    @garden_device.latitude = 0
    @garden_device.longitude = 0
  end
  
  def create
    @garden_device = current_user.garden_devices.build(params[:garden_device])
    if @garden_device.save
      ScheduleTypeLookup.all.each do |lu|
        schedule = DeviceSchedule.new
        schedule.sensor_flag = lu.flag
        schedule.frequency = 5
        schedule.garden_device = @garden_device
        schedule.is_enabled = (lu.flag == "u")
        schedule.save
      end
      redirect_to garden_devices_path
    else
      render 'new'
    end
  end
  
  def edit
    @garden_device = GardenDevice.find(params[:id])
  end
  
  def update
    @garden_device = GardenDevice.find(params[:id])
    if @garden_device.update_attributes(params[:garden_device])
      respond_to do |format|
        format.html {redirect_to garden_devices_path, :notice => "Garden Device was successfully updated."}
      end
    else
      respond_to do |format|
        format.html {render action: 'edit'}
      end
    end
  end
  
  def destroy
    @garden_device = current_user.garden_devices.find(params[:id])
    @garden_device.destroy
    respond_to do |format|
      format.html { redirect_to garden_devices_path }
    end    
  end
  
  def graphs
    @garden_device = GardenDevice.find(params[:id])
  end
end

app/helpers/garden_devices_helper.rb
module GardenDevicesHelper
end

app/views/garden_devices/_form.html.haml
= form_for @garden_device, :html => {:class => 'form-horizontal'} do |f|
  - if @garden_device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@garden_device.errors.count, "error")} prohibited this garden_device from being saved:"
      %ul
        - @garden_device.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :serial_number, :class => 'control-label'
    .controls
      = f.text_field :serial_number, :class => 'text_field'
  .control-group
    = f.label :timezone, :class => 'control-label'
    .controls
      = f.select :timezone, ActiveSupport::TimeZone.all.collect {|z| [z.to_s, z.name]}
  .control-group
    = f.label "Select Location", :class => 'control-label'
    .controls
      #mapdiv
        %p Loading
  .control-group
    = f.label :latitude, :class => 'control-label'
    .controls
      = f.text_field :latitude, :class => 'text_field', :readonly => true
  .control-group
    = f.label :longitude, :class => 'control-label'
    .controls
      = f.text_field :longitude, :class => 'text_field', :readonly => true
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      garden_devices_path, :class => 'btn'   
      
%script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCixO-MPiCirAciOE-EN3wkMUuPruLVfbc&sensor=false"}
%script{:type => "text/javascript"}
  loadMap(document.getElementById('mapdiv'), document.getElementById('garden_device_latitude'), document.getElementById('garden_device_longitude'));

app/views/garden_devices/edit.html.haml
%h1=  "Garden Device #{@garden_device.name}"
=render 'form'

app/views/garden_devices/graphs.html.haml
%h1= "Graphs for device #{@garden_device.name}"
  

%h3= "Temperature"
= google_chart('temperature_graph', 300, { :device_id => @garden_device.id })
%h3= "Humidity"
= google_chart('humidity_graph', 300, { :device_id => @garden_device.id })
%h3= "Light"
= google_chart('light_graph', 300, { :device_id => @garden_device.id })
  
.form-actions
  = link_to 'Back', garden_device_path(@garden_device), :class => 'btn btn-primary'

app/views/garden_devices/index.html.haml
%h1 My Garden Devices

%table.table.table-striped
  %thead
    %tr
      %th Device Name 
      %th Serial Number
      %th Owner
      %th Action
  %tbody
    - @garden_devices.each do |garden_device|
      %tr
        %td= garden_device.name
        %td= garden_device.serial_number
        %td= garden_device.user.get_full_name
        %td
          = link_to 'Show', garden_device, :class => 'btn btn-mini btn-info'
          = link_to 'Edit', edit_garden_device_path(garden_device), :class => 'btn btn-mini btn-warning'
          = link_to 'Delete', garden_device_path(garden_device),                                                                               |
                      :method => 'delete',                                                                            |
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure you want to delete?')), |
                      :class => 'btn btn-mini btn-danger'    
%p
  = paginate @garden_devices        
%p
  = link_to 'Add More Device', new_garden_device_path, :class=> "btn btn-primary"
  

app/views/garden_devices/new.html.haml
%h1 New Device
= render 'form'

app/views/garden_devices/show.html.haml
%h1= "Name: #{@garden_device.name}"
%h2="Serial: #{@garden_device.serial_number}"
%hr
%h2 Schedules
- if @garden_device.device_schedules.length > 0
  %table.table.table-striped
    %thead
      %tr
        %th Schedule Type
        %th Frequency
        %th Status
    %tbody
    - @garden_device.device_schedules.each do |schedule|
      %tr
        %td= ScheduleTypeLookup.find_by_flag(schedule.sensor_flag).get_name rescue nil
        %td= schedule.display_time
        %td
          - if schedule.is_enabled
            .label.label-success
              = "Enabled" 
          - else
            .label.label-important
              = "Disabled"
               
%h3 Update Schedule
= form_for(@device_schedule) do |f|
  = hidden_field_tag 'garden_device_id', @garden_device.id
  %table
    %tr
      %td= f.label :sensor_flag, "Schedule Type"
      %td= f.select :sensor_flag, ScheduleTypeLookup.all.collect {|s| [s.name, s.flag]}, {}, :onchange => "sensorTypeChanged(this)"
    %tr
      %td= f.label :frequency, "Frequency (in minutes)"
      %td= f.text_field :frequency, :onkeypress => "return numberonly(event,false)"
    %tr
      %td= f.label :is_enabled, "Enabled"
      %td= f.check_box :is_enabled, :onclick => "toggleFrequency(this)", :checked => true
    %tr
      %td
      %td= f.submit "Update Schedule", :class => "btn btn-primary"

.form-actions
  = link_to 'View Data Graph of this Device', graphs_path(@garden_device), :class => 'btn btn-primary'
  = link_to 'Edit Device', edit_garden_device_path(@garden_device), :class => 'btn btn-warning'
  = link_to 'Delete Device', garden_device_path(@garden_device),                                                                               |
              :method => 'delete',                                                                            |
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure you want to delete?')), |
              :class => 'btn btn-danger'    